# Generated by Django 5.0.6 on 2024-07-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id_operacji', models.AutoField(primary_key=True, serialize=False)),
                ('ilosc', models.CharField(blank=True, null=True)),
                ('nazwa', models.CharField(blank=True, null=True)),
                ('cena', models.CharField(blank=True, null=True)),
                ('wlasciciel', models.CharField(blank=True, null=True)),
                ('zakup_sprzedaz', models.CharField(blank=True, db_column='zakup/sprzedaz', null=True)),
            ],
            options={
                'db_table': 'Operation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(blank=True, db_column='Imie', null=True)),
                ('nazwisko', models.CharField(blank=True, db_column='Nazwisko', null=True)),
                ('saldo', models.CharField(blank=True, db_column='Saldo', null=True)),
                ('id_akcji', models.CharField(blank=True, db_column='ID_akcji', null=True)),
            ],
            options={
                'db_table': 'User',
                'managed': False,
            },
        ),
    ]
